{% set name = "cursor" %}
{% set version = "1.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6758cae6ac14765ec85d9ce3f14fcb98fff5045f06d8398f1e8da8ce3acd2f20

build:
  entry_points:
    - cursor_hide = cursor:hide
    - cursor_show = cursor:show
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    # check requirements
    - python -m pip check
    # check entry points
    - cursor_hide
    - cursor_show

about:
  home: https://github.com/GijsTimmers/cursor
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A small Python package to hide or show the terminal cursor

extra:
  recipe-maintainers:
    - duncanmmacleod
